name: Semantic release

on:
  push:
    branches:
      - main

jobs:
  versioning:
    uses: GEWIS/actions/.github/workflows/versioning.yml@v1
    permissions:
      contents: write
      issues: write
      pull-requests: write

  release:
    uses: GEWIS/actions/.github/workflows/docker-release-ghcr.yml@v1
    permissions:
      contents: read
      packages: write
    needs: versioning
    if: ${{ needs.versioning.outputs.next-version != '' }}
    with:
      projects: '["."]'
      docker-paths: '["board/google-calendar-to-mailcow"]'
      version: ${{ needs.versioning.outputs.next-version }}
